apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: persistence-volume-claim-template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${JENKINS_PVC_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
    storageClassName: ${STORAGE_CLASS_NAME}
parameters:
- description: Name of PVC
  displayName: PVC name
  name: JENKINS_PVC_NAME
  required: true
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
- description: Storage Class Name of PVC.
  displayName: Storage Class Name
  name: STORAGE_CLASS_NAME
  required: true